---
- name: Ping for Server of LT Env
  hosts: LTMNTCNT
  gather_facts: true

  tasks:
  - name: Pinging for Linux Servers
    ping:
    when: ansible_system == 'Linux'

  - name: Pinging for Windows Servers
    win_ping:
    when: ansible_system == 'Wini32NT'
