---
- name: Shutdown Server of Zabbix Member
  hosts: LTMNTALL
  gather_facts: true

  tasks:
    - name: Shutdown Linux Server wait 60sec
      command: shutdown -h -t 60
      when: ansible_system == "Linux"

    - name: Shutdown Windows Server
      win_shell: Stop-Computer
      when: ansible_system == "Win32NT"

