---
- name: Change Hostname
  hosts: OthZabbixMembers
  gather_facts: true
#  remote_user: root
#  sudo: yes

  tasks:
    - name: Install libselinux_python for CentOS 6.x
      yum:
        name: libselinux-python
        state: installed
      when: 
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "6"
