---
#=================================================
#
# Role-Task: windows_update/tasks/main.yml
#
#=================================================

- win_updates:
    category_names:
      - Application
      - CriticalUpdates
      - DefinitionUpdates
      - FeaturePacks
      - SecurityUpdates
      - ServicePacks
      - Update Rollups
      - Updates
    state:
      installed
    reboot:
      yes
    whitelist:
      
