---
#=================================================
#
# role: repository/tasks/installRepository.yml
#
#=================================================


#- name: ### debug pkgBrnchNum ###
#  debug: var=pkgBrnchNum


- name: Install Zabbix Repository for RHEL
  yum:
    name: "{{ zabbix_Base_Url }}/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-{{ spcfyMjVer }}-{{ repoBrnchNum }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when:
    low_distribution == "rhel"

- name: "Install Zabbix {{spcfyMjVer}} Repository for {{ansible_distribution}}"
  apt:
    deb: "/tmp/zabbix-release_{{spcfyMjVer}}-{{repoBrnchNum}}+{{ansible_distribution_release}}_all.deb"
  when:
    ("debian" == low_distribution)
    or ("ubuntu" == low_distribution)

- name: Repository make cache
  shell: apt update
  when:
    ("debian" == low_distribution)
    or ("ubuntu" == low_distribution)


