---
- name: call other Playbook
  hosts: ansible_tower
  gather_facts: true

  tasks:
  - name: get Date
    shell: date

  - name: call
    shell: "ansible-playbook /root/Playbooks/Parts/test.yml "
    register: result

  - debug:
      var: result
