---
- name: Change Hostname
  hosts: OTHALL
  gather_facts: true

  tasks:
    - name: Install libselinux_python for CentOS 6.x
      yum:
        name: libselinux-python
        state: installed
      when: 
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "6"
