---
- name: create user on mysql
  hosts: 192.168.56.32

  tasks:
  - name: mysql user add
    mysql_user:
      name:           zabbix
      host:           localhost
      password:       zabbix
      append_privs:   yes
      login_user:     root
      priv:           zabbix.*:ALL,GRANT

  
