---
#=================================================
#
# Role-Task: httpd/tasks/startHttpd.yml
#
#=================================================

- name: Restart httpd
  service:
    name:    httpd
    state:   restarted

