---
#=================================================
#
# Host_Vars: 10.2.21.90.yml (LTCnt610)
#
#=================================================

ServerIP:       10.6.21.34,10.6.21.23
ServerActiveIP: 10.6.21.34

