---
#=================================================
#
# Host_Vars: OthPx01.yml
#
#=================================================

ansible_ssh_user: root
ansible_ssh_pass: ZAQwsx123

Px_Specify_Ver:  3.0.28
Agt_Specify_Ver: 3.0.28

PxServerIP:       10.2.22.11
ServerIP:         10.2.22.21
ServerActiveIP:   10.2.22.21
HostMetadataItem: system.sw.os

DBRootUsr:             root
DBRootPwd:             toor

# Proxy Config Setting Value
DBName:             zabbix_proxy
DBUser:             zabbix
DBPassword:         zabbix
ProxyLocalBuffer:   24
ProxyOfflineBuffer: 24
ConfigFrequency:    600
Timeout:            10

isSv: False
