---
#=================================================
#
# Role-Task: php/tasks/changePhpIni.yml
#
#=================================================

- name: Replaced Timezone in php.ini
  replace:
    path:    "/etc/php.ini"
    regexp:  "^(;|)date.timezone.*$"
    replace: "date.timezone = Asia/Tokyo"

