- name: OS Judge
  hosts: LTZPx01Mbr, LTZPx03Mbr

  tasks:
  - name: case of CentOS 6.x
    debug:
      msg: "centos 6.x  desu"
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

  - name: case of CentOS 7.x
    debug:
      msg: "centos 7.x desu"
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

  - name: case of Ubuntu
    debug:
      msg: "ubuntu desu"
    when: ansible_distribution == 'Ubuntu'

  - name: case of Debian 
    debug:
      msg: "debian desu"
    when: ansible_distribution == 'Debian'

